name: "nfs-server"
description: "a nfs server"
version: "1.0.0-rancher2"
category: "Storage"
maintainer: "Actano RPLAN Next Team"
license: "custom"
projectURL: "https://github.com/actano/rancher-catalog"
